### ISSUE TITLE
Could not select Device

### ISSUE THREAD

**Issue by kraeml** [alexanderkunz/AEC-Webserver#1]
Hey I installed AEC-Webserver on my Pi. The Webserver is running but in the Browser I could not select any device. Its empty.

```
python webserver.py 
Bottle v0.12.13 server starting up (using WSGIRefServer())...
Listening on http://0.0.0.0:8080/
Hit Ctrl-C to quit.

192.168.56.216 - - [17/Apr/2019 21:22:29] "GET / HTTP/1.1" 200 813
192.168.56.216 - - [17/Apr/2019 21:22:29] "GET /graph.png HTTP/1.1" 200 2552
192.168.56.216 - - [17/Apr/2019 21:23:29] "GET / HTTP/1.1" 200 813
192.168.56.216 - - [17/Apr/2019 21:23:30] "GET /graph.png HTTP/1.1" 200 2552
192.168.56.216 - - [17/Apr/2019 21:24:30] "GET / HTTP/1.1" 200 813
192.168.56.216 - - [17/Apr/2019 21:24:30] "GET /graph.png HTTP/1.1" 200 2552
192.168.56.216 - - [17/Apr/2019 21:25:30] "GET / HTTP/1.1" 200 813
192.168.56.216 - - [17/Apr/2019 21:25:30] "GET /graph.png HTTP/1.1" 200 2552
```

With demesg I could see the uart:

```
usb 1-1.2: ch341-uart converter now attached to ttyUSB0
```

When I run `python serialtest.py` ther is still nothing.

Any idea what I make wrong.

Run with sudo. No
Run with python3. No
Run with pyhton3 and sudo. No

kraeml

**Comment by alexanderkunz** [comment]
In `serialtest.py` you'll have to change the port to `/dev/ttyUSB0` or whatever your port currently is (be careful, sometimes it can change to `/dev/ttyUSB1` etc. when being replugged (too fast). It should print all incoming messages, given that they can be read properly.
Be aware that the devices only send information every X minutes (might be every 15 minutes, I don't rember), and you'll have to wait for every device to send a status update for them to appear in the devices list. The devices list will also be empty if no status messages ever arrive.

I hope your devices are compatible with this software. To make sure you're actually receiving data, you could add `print(cur)` after line 21 in `serialparser.py` for testing to see if you're receiving data there.  You could also just do `cat /dev/ttyUSB0` from terminal and see what happens.
